# https://github.com/mochajs/mocha/blob/master/example/config/.mocharc.yml
extension:
  - js
ignore:
  - coverage
  - lib
  - node_modules
  - .nyc_output
reporter: spec
require: '@babel/register'
spec: spec/**/*.spec.js
watch-files:
  - spec/**/*.js
  - src/**/*.js
watch-ignore:
  - coverage
  - lib
  - node_modules
  - .nyc_output
